/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    public static void main(String[] args) {
        long t1 = 0;
        long t2 = 0;
        long total = 0;
        long c = 0;
        int i = 1;

        while (c < 4000000) {
            if (i == 1) {
                t2 = 1;
            } else if (i == 2) {
                t1 = 2;
                total += t1;
            } else {
                c = t1 + t2;
                
                if (c % 2 == 0) {
                    total += c;
                }
                
                t2 = t1;
                t1 = c;
            }

            i++;
        }

        System.out.println(total);
    }

}
